CREATE TABLE IF NOT EXISTS bank_accounts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50),
    routing_number VARCHAR(20) NOT NULL,
    nin VARCHAR(20) NOT NULL,
    account_number VARCHAR(20) NOT NULL,
    bank_name VARCHAR(30)
);