CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    bank_account_id INTEGER NOT NULL,
    status VARCHAR(10) NOT NULL,
    type VARCHAR(10) NOT NULL,
    parent_transaction_id INTEGER,
    /* CHECK (status in ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')),
    CHECK (type in ('WITHDRAWAL', 'REFUND')), */
    FOREIGN KEY (parent_transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id)
);

CREATE TABLE IF NOT EXISTS transaction_components (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_id INTEGER NOT NULL,
    type VARCHAR(10) NOT NULL,
    value DECIMAL NOT NULL,
    /* CHECK type_options (type in ('NET_AMOUNT', 'FEE')), */
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
);